export const metadata = {
  title: "Safarish - Resorts to stay",
  description: "Generated by create next app",
};

export default function ResortsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
